# Default values for legacy-qemu-vm.

image:
  repository: docker-registry.domain.com
  path: qemu/qemu-fedora
  pullPolicy: IfNotPresent

vm:
  # machineUuid: "No default"
  # host: "No default"
  # mac: "Optional"
  spicePort: 5901
  efiBoot: true
  secureBoot: false
  useTpm: false
  maximumCpus: 4
  currentCpus: 2
  # Specify using string (too big, will be converted to float) 
  maximumMemory: "8589934592"
  currentMemory: "8589934592"
  disks:
  - device: /dev/vg/lv
    size: 40Gi