# Default values for legacy-qemu-vm.

image:
  repository: docker-registry.domain.com
  path: qemu/qemu-fedora:latest
  pullPolicy: Always

vm:
  # machineUuid: "No default"
  # host: "No default"
  # mac: "Optional"
  spicePort: 5901
  efiBoot: true
  secureBoot: false
  useTpm: false
  disks:
  - device: /dev/vg/lv
    size: 40Gi