kind: Pod
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: qemu-vm
    vm: {{ .Release.Name }}
spec:
  containers:
  - name: {{ .Release.Name }}
    image: {{ .Values.image.repository }}/{{ .Values.image.path }}:{{ .Values.image.version }}
    resources: {}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    # Not needed because pod is priviledged:
    # - mountPath: /dev/kvm
    #   name: dev-kvm
    # - mountPath: /dev/net/tun
    #   name: dev-tun
    # - mountPath: /sys/fs/cgroup
    #   name: cgroup
    - mountPath: /var/local/qemu
      name: qemu
    volumeDevices:
    {{- range $index, $disk := .Values.vm.disks }}
    - devicePath: /dev/disk-{{ $index }}
      name: disk-{{ $index }}
    {{- end }}
    securityContext:
      privileged: true
    command:
    - /bin/bash
    - -xc
    - |
      ovmf_code_path=/usr/share/OVMF/OVMF_CODE.fd
      if [ ! -r "$ovmf_code_path" ]; then
          # Arch Linux
          ovmf_code_path=/usr/share/edk2/x64/OVMF_CODE.fd
      fi
      
      # Create taps for bridges
      declare -A taps
      declare -A tap_macs
      {{- range $index, $network := .Values.vm.networks }}
      {{- if hasKey $network "bridge" }}
      i=1
      while [ $i -lt 10 ]; do
        tap=tap$i
        if ip tuntap add mode tap $tap; then
          ip link set $tap up
          brctl addif {{ if hasKey $network.bridge "name" }}{{ $network.bridge.name }}{{ else }}br0{{ end }} $tap
          taps[$tap]={{ if hasKey $network.bridge "name" }}{{ $network.bridge.name }}{{ else }}br0{{ end }}
          break;
        fi
        i=$((i+1))
      done
      {{- if $network.bridge.mac }}
      tap_macs[$tap]="{{ $network.bridge.mac }}"
      {{- end }}
      {{- end }}
      {{- end }}
      
      # Create network arguments
      qemu_network_args=()
      i=1
      for tap in ${!taps[@]}; do
        qemu_network_args+=( -netdev tap,id=hostnet$i,ifname=$tap,script=no,downscript=no )
        mac=""
        if [ ! -z ${tap_macs[$tap]} ]; then
          mac=",mac=${tap_macs[$tap]}"
        fi
        qemu_network_args+=( -device virtio-net-pci,id=net$i,netdev=hostnet$i$mac )
        i=$((i+1))
      done
      
      qemu_args=(
        -no-user-config
        -name guest={{ .Release.Name }},debug-threads=on
        -uuid {{ required "Valid .Values.vm.machineUuid entry required" .Values.vm.machineUuid }}
        -machine pc-q35-6.2,usb=off,vmport=off,{{ if .Values.vm.secureBoot }},smm=on{{ end }}dump-guest-core=off{{ if .Values.vm.efiBoot }},pflash0=efi-bios-rom-device,pflash1=efi-bios-eeprom-device{{ end }},memory-backend=pc.ram,hpet=off
            {{- if .Values.vm.secureBoot }}
            -global driver=cfi.pflash01,property=secure,value=on 
            -object '{"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/local/qemu/master-key.aes"}'
            {{- end }}
            {{- if .Values.vm.efiBoot }}
            -blockdev '{"node-name":"efi-bios-rom-backend","driver":"file","filename":"'${ovmf_code_path}'","auto-read-only":true,"discard":"unmap"}'
            -blockdev '{"node-name":"efi-bios-rom-device","driver":"raw","read-only":true,"file":"efi-bios-rom-backend"}'
            -blockdev '{"node-name":"efi-bios-eeprom-backend","driver":"file","filename":"/var/local/qemu/EFI_VARS.fd","auto-read-only":true,"discard":"unmap"}'
            -blockdev '{"node-name":"efi-bios-eeprom-device","read-only":false,"driver":"raw","file":"efi-bios-eeprom-backend"}'
            {{- end }}
            {{- if .Values.vm.useTpm }}
            -chardev socket,id=chrtpm,path=/run/swtpm-sock
            -tpmdev emulator,id=tpm0,chardev=chrtpm 
            -device tpm-tis,tpmdev=tpm0
            {{- end }}
            -object '{"id":"pc.ram","qom-type":"memory-backend-ram","size":{{ .Values.vm.maximumMemory }}}'
        -cpu host,migratable=on
        -smp {{ .Values.vm.currentCpus }},maxcpus={{ .Values.vm.maximumCpus }},sockets={{ .Values.vm.maximumCpus }},cores=1,threads=1
        -m {{ div .Values.vm.maximumMemory 1048576 }}
        -accel kvm
        -global kvm-pit.lost_tick_policy=delay
        -overcommit mem-lock=off
        -chardev socket,id=charmonitor,path=/var/local/qemu/monitor.sock,server=on,wait=off
        -mon chardev=charmonitor,id=monitor,mode=control
        -rtc base=utc,driftfix=slew
        -global ICH9-LPC.disable_s3=1
        -global ICH9-LPC.disable_s4=1
        -boot strict=on
        -device qemu-xhci,p2=15,p3=15,id=usb
        -device virtio-serial-pci,id=virtio-serial0
        {{- range $index, $disk := .Values.vm.disks }}
        -device virtio-blk-pci,drive=drive-{{ $index }}-device,id=virtio-disk{{ $index }},bootindex={{ add $index 1 }}
        -blockdev '{"node-name":"drive-{{ $index }}-backend","driver":"host_device","filename":"/dev/disk-{{ $index }}","aio":"native","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}'
        -blockdev '{"node-name":"drive-{{ $index }}-device","read-only":false,"driver":"raw","file":"drive-{{ $index }}-backend"}'
        {{- end }}
        ${qemu_network_args[@]}
        -chardev pty,id=charserial0
        -device isa-serial,chardev=charserial0,id=serial0,index=0
        -chardev socket,id=charchannel0,path=/var/local/qemu/org.qemu.guest_agent.0,server=on,wait=off
        -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0
        -chardev spicevmc,id=charchannel1,name=vdagent
        -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charchannel1,id=channel1,name=com.redhat.spice.0
        -audiodev '{"id":"audio1","driver":"spice"}'
        -spice port={{ .Values.vm.spicePort }},addr=0.0.0.0,disable-ticketing=on,seamless-migration=on
        -device virtio-vga,id=video0,max_outputs=1
        -device ich9-intel-hda,id=sound0
        -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0,audiodev=audio1
        -chardev spicevmc,id=charredir0,name=usbredir
        -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2
        -chardev spicevmc,id=charredir1,name=usbredir
        -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3
        -device virtio-balloon-pci,id=balloon0
        -object '{"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"}'
        -device virtio-rng-pci,rng=objrng0,id=rng0
        -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=allow,resourcecontrol=deny 
        -msg timestamp=on          
      )
      
      shutdownVM() {
          echo Shutting down VM
          socat - unix-connect:/var/local/qemu/monitor.sock <<- EOD
      { "execute": "qmp_capabilities" }
      { "execute": "system_powerdown" }
      EOD
      }
      
      trap shutdownVM SIGTERM
      
      {{- if .Values.vm.useTpm }}
      
      echo Starting software TPM2...      
      swtpm socket --tpm2 \
        --tpmstate dir=/var/local/qemu \
        --ctrl type=unixio,path=/run/swtpm-sock,mode=0600 \
        --terminate \
        &
        
      while [ ! -r /run/swtpm-sock ]; do
        sleep 1;
      done
      {{- end }}
      
      echo Starting VM...
      /usr/bin/qemu-system-x86_64 ${qemu_args[@]} &
      qemu_pid=$!

      {{- if .Values.vm.currentMemory }}
      
      echo Adjusting balloon...
      sleep 1
      socat - unix-connect:/var/local/qemu/monitor.sock <<- EOD
      { "execute": "qmp_capabilities" }
      { "execute": "balloon", "arguments": { "value": {{ .Values.vm.currentMemory }} } }
      EOD
      sleep 1
      {{- end }}
      
      while true; do
        wait $qemu_pid
        wait_result=$?
        if [ $wait_result -le 128 ]; then
          # Exists no longer or has terminated
          break
        fi
        # wait has been interrupted
      done
      echo VM has terminated
      
      # Cleaning up
      for tap in ${!taps[@]}; do
        brctl delif ${taps[$tap]} $tap
        ip link set $tap down
        ip tuntap delete mode tap $tap
      done
  volumes:
  # Not needed because pod is priviledged:
  # - name: dev-kvm
  #   hostPath:
  #     path: /dev/kvm
  #     type: CharDevice
  # - hostPath:
  #     path: /dev/net/tun
  #     type: CharDevice
  #   name: dev-tun
  # - name: cgroup
  #   hostPath:
  #     path: /sys/fs/cgroup
  - name: qemu
    hostPath:
      path: /var/local/qemu/guests/{{ .Release.Name }}
  {{- range $index, $disk := .Values.vm.disks }}
  - name: disk-{{ $index }}
    persistentVolumeClaim:
      claimName: {{ $.Release.Name }}-pvc-{{ $index }}
  {{- end }}
  hostNetwork: true
  terminationGracePeriodSeconds: 60
  restartPolicy: Never
